version: '3.8'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: e_commerce_prod
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      RAILS_ENV: production
    volumes:
      - .:/e-commerce
    ports:
      - "80:3000"
    depends_on:
      - db
