version: '3.4'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      RAILS_ENV: production
      SECRET_KEY:
    volumes:
      - .:/e-commerce
    ports:
      - "80:3000"
    env_file: .env
    depends_on:
      - db
