version: '3.4'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: e_commerce_prod
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      SECRET_KEY:
    volumes:
      - .:/e-commerce
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "80:3000"
    env_file: .env
    depends_on:
      - db
