version: '3.8'
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_DB: e_commerce_prod
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/e-commerce
    ports:
      - "80:3000"
    depends_on:
      - db
