default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || 'e_commerce_dev' %>
  port:     <%= ENV['DATABASE_PORT'] || 5432 %>
  host:     <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  development:
    <<: *default
    database: e_commerce_dev

  test: &test
    <<: *default
    database: e_commerce<%= ENV['TEST_ENV_NUMBER'] %>

  production: &production
    <<: *default
    database: e_commerce
