default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.config[:DATABASE_NAME] || 'e_commerce_dev' %>
  port:     <%= Rails.application.credentials.config[:DATABASE_PORT] || 5432 %>
  host:     <%= Rails.application.credentials.config[:DATABASE_HOST] || 'localhost' %>
  username: <%= Rails.application.credentials.config[:DATABASE_USERNAME] || '' %>
  password: <%= Rails.application.credentials.config[:DATABASE_PASSWORD] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: e_commerce_dev

test: &test
  <<: *default
  database: e_commerce_test

production: &production
  <<: *default
  database: e_commerce
  username: rails
